# Numpy 

## Python Library used for working with Arrays. It also have functions for working with Linear Algebra, Matrices and Fourier Transformation

Source Code : https://github.com/numpy
installation : pip install numpy (terminal) // !pip install numpy (jupyter)


In [3]:
#importing numpy library 

import numpy as np

In [5]:
#creating an array

arr1 = np.array([2,4,6,8])
print(arr1)


type(arr1)

[2 4 6 8]


numpy.ndarray

In [6]:
#check version of numpy
print(np.__version__)

1.26.4


In [8]:
#we can pass both lists and tuples to np.array() fuction to convert them to arrays

arr2 = np.array([3,2,1,4,5,7]) #passing list 
print(arr2)

arr3 = np.array((1,4,5,1,2,9)) #passing tuple
print(arr3)

[3 2 1 4 5 7]
[1 4 5 1 2 9]


## Dimensions in Array:
### 0D Array
### 1D Array
### 2D Array
### 3D Array

In [11]:
# 0D Array
a = np.array(30)
print("0D Array: ")
print(a)

#1D Array
b = np.array([1,2,3,4,5,7])
print("1D Array: ")
print(b)

#2D Array
c = np.array([[10,20,30,40,50],[11,12,13,14,15]])
print("2D Array: ")
print(c)


#3D Array
d = np.array([[[100,200,300,400,500],[101,102,103,104,105]],[[50,60,70,80,90],[40,30,90,20,22]]])
print("3D Array: ")
print(d)

0D Array: 
30
1D Array: 
[1 2 3 4 5 7]
2D Array: 
[[10 20 30 40 50]
 [11 12 13 14 15]]
3D Array: 
[[[100 200 300 400 500]
  [101 102 103 104 105]]

 [[ 50  60  70  80  90]
  [ 40  30  90  20  22]]]


#### We can check number of dimensions an Array have by using "ndim" attribute of Arrays

In [13]:
print("Dimensions Of Array a :",a.ndim)
print("Dimensions Of Array b :",b.ndim)
print("Dimensions Of Array c :",c.ndim)
print("Dimensions Of Array d :",d.ndim)

Dimensions Of Array a : 0
Dimensions Of Array b : 1
Dimensions Of Array c : 2
Dimensions Of Array d : 3


### "ndmin = __" can be used as an argument to "np.array" function to define number of dimensions to an Array

In [15]:
arr11 = np.array([1,3,4,5], ndmin=5)
print(arr11)
print("Dimmensions of arr11 : ",arr11.ndim)

[[[[[1 3 4 5]]]]]
Dimmensions of arr11 :  5


## Arrays use indexing 
### it works by assigning a numerical value to each each element of an array starting from 0 to no_of_elements-1 

Example: 
        
Array:  |  10  |  20   |  30  |  40   |

number of elements = 4

index 0 - 3

0-->10

1-->20

2-->30

3-->40

In [22]:
# access elements of 1-D array using index

ar1 = np.array([100,2,3,4,6,7])

print(ar1[0]) #this will print element at index 0

print(ar1[4]+ar1[5]) #this will print sum of elements at index 4 and 5

#we can iterate through arrays using loops
for i in ar1:
    print(i, end=" ")

100
13
100 2 3 4 6 7 

In [24]:
#access elements of 2-D array using index

ar2 = np.array([[1,2,3,4,5],[10,20,30,40,50]])
print("2nd lement on row 2 is : ", ar2[1,1])

2nd lement on row 2 is :  20


In [25]:
#access elements of 3-D arrays using index

ar3 = np.array([[[8,7,6],[5,4,7]],[[2,5,3],[9,2,6]]])

print(ar3[1,0,2])

3


#### Explination of accesing 3-D arrays:

ar3[1,0,2] prints value 3

first number represents first Dimension which contain 2 arrays from which this part is selected " [[2,5,3],[9,2,6]] "

second number represents second Dimension which also contains 2 arrays from which this is selected " [2,5,3] "

third number represents third dimension which conatins 3 elements from which this element is selected " 3 "

## We can use negative indexing to access array elements 

Example: 
        
Array:  |  10  |  20   |  30  |  40   |

number of elements = 4

negative index -4 to -1

-4-->10

-3-->20

-2-->30

-1-->40

In [27]:
ar3 = np.array([7,8,9,10])

print("element at index -1 = ", ar3[-1])
print("element at index -4 = ", ar3[-4])

element at index -1 =  10
element at index -4 =  7


# Slicing Arrays:

### Slicing means taking a part of array 
### array[start index : end index] this will return a part of array betweeen these indexes

In [36]:
aar1 = np.array([3,6,4,2,4,3,7,9])

#this will print a slice of orginal array
print(aar1[2:6])

[4 2 4 3]



We can add one more attribute to slicing as steps 

array[start index : end index : steps]

In [37]:
#this example will make you understand what step attribute actually do

aar2 = np.array([1,2,3,4,5,6,7,8,9,10])

print(aar2[0:9:1]) #this will print elemts between 0 and 9 with jump of 1 

print(aar2[0:9:2]) #this will print elemts between 0 and 9 with jump of 2  

print(aar2[0:9:3]) #this will print elemts between 0 and 9 with jump of 3

[1 2 3 4 5 6 7 8 9]
[1 3 5 7 9]
[1 4 7]


In [38]:
# Some crazy Things can be done like reversing the array an be done using slicing technique

aar3 = np.array([1,2,3,4,5])
#this will reverse the array
print(aar3[::-1])

[5 4 3 2 1]


# Data Tyes in Numpy:

i---integer

b---boolean

u---unsigned integer

f---float

c---complex float

m---timedelta

M---datetime

O---object

S---string

U---unicode string

V---void

#### we can use "dtype" to check data type array

In [39]:
aar4 = np.array([3,4,2,1])
print(aar4.dtype)

int64


In [41]:
aar5 = np.array(['shahid','arshid','ubaid'])
print(aar5.dtype)

<U6


In [42]:
aar6 = np.array([3.3,4.5,2.5,1.5])
print(aar6.dtype)

float64


In [43]:
aar7 = np.array([True,False])
print(aar7.dtype)

bool


# View and Copy Functions

#### View : it creates a view of array ---- "array.view()"

#### Copy : it creates another copy of an array ----- "array.copy()"

In [45]:
# View function
a1 = np.array([10,15,20,25])

x = a1.view() #this will create a view of original array

a1[0] = 20 
#changing contents of original array will affect the view also

print(a1)
print(x)

[20 15 20 25]
[20 15 20 25]


In [46]:
# Copy function 
a2 = np.array([10,15,20,25])

y = a1.copy() #this will create a view of original array

a1[0] = 20 
#changing contents of original array will not affect contents of copied array

print(a2)
print(y)

[10 15 20 25]
[20 15 20 25]


# Numpy Array Shape
### Shape of an Array defines the number of elements in each dimension
#### Numpy Arrays have an attributes "shape" that returns the shape of an array

In [3]:
a2 = np.array([2,3,4,5])
print(a2.shape)

(4,)


In [4]:
a3 = np.array([[2,3,4,5],[4,4,3,2]])
print(a3.shape)

(2, 4)


In [8]:
a4 =np.array([9,1,2,4,6],ndmin=5) #we have created an array with 5 dimnsions
print(a4)
print(a4.shape)

[[[[[9 1 2 4 6]]]]]
(1, 1, 1, 1, 5)


#### We can reshape existing arrays using "reshape" function
##### "array.reshape()"

In [15]:
#Reshape from 1-D to 2-D & 3-D

a5 = np.array([11,12,13,14,15,16,17,18,19,20,21,22])
a5_2d = a5.reshape(4,3)
a5_3d = a5.reshape(2,3,2)
print("1-D: \n",a5)
print("2-D: \n",a5_2d)
print("3-D: \n",a5_3d)

1-D: 
 [11 12 13 14 15 16 17 18 19 20 21 22]
2-D: 
 [[11 12 13]
 [14 15 16]
 [17 18 19]
 [20 21 22]]
3-D: 
 [[[11 12]
  [13 14]
  [15 16]]

 [[17 18]
  [19 20]
  [21 22]]]


#### There are more functions to reshape array like: 
#### "flatten" / "ravel"
#### Functins for rearranging the elements of array like:
#### "rot90" / "flip" / "fliplr" / "flipud" 

# Numpy Array Iterating

In [19]:
#iterating 1-D arrays

a6 = np.array([2,3,4,5])
for i in a6:
    print(i)

2
3
4
5


In [20]:
# iterating 2-D arrays
a7 = np.array([[2,3,4,5],[4,4,3,2]])

#this will return the whole 1-D arrays 
for i in a7:
    print(i)
    
# if we want to iterate over elements of array 
for i in a7:
    for j in i:
        print(j)

[2 3 4 5]
[4 4 3 2]
2
3
4
5
4
4
3
2


In [22]:
#iteratin 3-D arrays

a8 = np.array([[[8,7,6],[5,4,7]],[[2,5,3],[9,2,6]]])

for i in a8:
    print(i)

print(" ")
for i in a8:
    for j in i:
        print(j)
        
        
print(" ")
for i in a8:
    for j in i:
        for k in j:
            print(k)

[[8 7 6]
 [5 4 7]]
[[2 5 3]
 [9 2 6]]
 
[8 7 6]
[5 4 7]
[2 5 3]
[9 2 6]
 
8
7
6
5
4
7
2
5
3
9
2
6


## Joining Numpy Arrays:

### using "concatenate()" function 

In [28]:
a9 = np.array([2,3,4,5])

a10 = np.array([6,7,8,9])

newarr1 = np.concatenate((a9, a10))
print(newarr1)

[2 3 4 5 6 7 8 9]


In [29]:
a11 = np.array([[2,3,4],[5,3,1]])

a12 = np.array([[6,7,8],[9,2,4]])

newarr2 = np.concatenate((a11, a12))
print(newarr2)

#sing axis attribue
print("using 'axis' attribue")
newarr3 = np.concatenate((a11, a12),axis=1)
print(newarr3)

[[2 3 4]
 [5 3 1]
 [6 7 8]
 [9 2 4]]
using 'axis' attribue
[[2 3 4 6 7 8]
 [5 3 1 9 2 4]]


#### Using "stack()" function
#### stack function has some helper functions:
#### hstack() --- stack along row
#### vstack() --- stack along columns
#### dstack() --- stack along height

In [31]:
a13 = np.array([2,3,4,5])

a14 = np.array([6,7,8,9])

newarr4 = np.stack((a13, a14),axis=1)
print(newarr4)

[[2 6]
 [3 7]
 [4 8]
 [5 9]]


In [32]:
# hstack()

a15 = np.array([2,3,4,5])

a16 = np.array([6,7,8,9])

newarr5 = np.hstack((a15, a16))
print(newarr5)

[2 3 4 5 6 7 8 9]


In [33]:
# vstack

a17 = np.array([2,3,4,5])

a18 = np.array([6,7,8,9])

newarr6 = np.vstack((a17, a18))
print(newarr6)

[[2 3 4 5]
 [6 7 8 9]]


In [35]:
# dstack

a19 = np.array([2,3,4,5])

a20 = np.array([6,7,8,9])

newarr7 = np.dstack((a19, a20))
print(newarr7)

[[[2 6]
  [3 7]
  [4 8]
  [5 9]]]


# Numpy Array functions to generate array of zeros or ones
### np.zeros(shape, dtype,order)
### np.ones(shape, dtype,order)

In [6]:
za = np.zeros([6,2],dtype=int)
print(za)

[[0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]]


In [10]:
oa = np.ones([3,2,3],dtype=float)
print(oa)

[[[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]]
